name: pyconza-dad
channels:
  - conda-forge
  - defaults
dependencies:
  - bokeh=2.4.3
  - geopandas=0.11.1
  - holoviews=1.15.0
  - hvplot=0.8.1
  - jupyterlab=3.4.7
  - matplotlib=3.6.0
  - numpy=1.23.3
  - panel=0.13.1
  - geoviews
  - pip=22.2.2
  - python=3.10.6
  - scikit-learn=1.1.2
  - pip:
    - black==22.10.0
    - dvc==2.29.0
    - flake8==5.0.4
    - ipytest==0.12.0
    - mypy==0.982
    - pandas==1.3.5
    - pandas-stubs==1.5.0.221010
    - prefect==2.4.5
    - pyarrow==9.0.0
    - pytest==7.1.3